/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HeaderArea: typeof import('./components/HeaderArea.vue')['default']
    HomeArea: typeof import('./pages/HomeView.vue')['default']
    HomePage: typeof import('./pages/HomeView.vue')['default']
    PageNavigator: typeof import('./components/PageNavigator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
